---
title: "Luxembourg Research Evaluation 2022"
author: "Daniel S. Hain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: no
  html_notebook:
    df_print: paged
    toc: no
    code_folding: hide
---

```{r setup, include=FALSE}
### Generic preamble
rm(list=ls())
Sys.setenv(LANG = "en")
options(scipen = 5)
set.seed(1337)

### Load packages  
library(knitr) # For display of the markdown
library(kableExtra) # For table styling

library(tidyverse)
library(magrittr)

### Extra packages
library(bibliometrix)
library(tidygraph)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      message = FALSE)
```

```{r, include=FALSE}
var_inst <- 'LISER'
var_dept <- 'UD'
```

# General Data Prep

```{r}
data_scival_dept <- read_csv2(paste0('../../data/scival_', str_to_lower(var_inst), '_', str_to_lower(var_dept), '.csv')) 
colnames(data_scival_dept) <- colnames(data_scival_dept) %>% str_to_lower() %>% str_squish() %>% str_replace_all("[ ]", "_") %>% str_remove_all('[()\\*\\.\\,]')
```

```{r}
# save all
read_csv(paste0('../../data/scopus_', str_to_lower(var_inst), '.csv')) %>% 
  semi_join(data_scival_dept, by = c('DOI' = 'doi') ) %>%
  write_csv( paste0('../../data/scopus_', str_to_lower(var_inst), '_', str_to_lower(var_dept), '_seed_0.csv'))
```


```{r}
M <- convert2df(file = paste0('../../data/scopus_', str_to_lower(var_inst), '.csv'), dbsource = "scopus", format = "csv") %>%
  # Filter out other departments only.
  semi_join(data_scival_dept, by = c('DI' = 'doi')) 
```

NOTE: N falls from 220 to 163 for LISER UD. Reason?
Maybe observation periods, check...

```{r}
# create label
M %<>% rownames_to_column('XX') %>% 
  mutate(XX = paste(str_extract(XX, pattern = ".*\\d{4}"), str_sub(TI, 1,25)) %>% str_replace_all("[^[:alnum:]]", " ") %>% str_squish() %>% str_replace_all(" ", "_") %>% make.unique(sep='_')) %>%
  # filter for publications with enough references
  mutate(CR_n = CR %>% str_count(';')) %>%
  filter(CR_n > 5) %>%
  # Filter for the oines with abstract
  filter(AB != '') %>%
  filter(AB %>% str_length() > 25) %>%
  # GEnerate TC_year
  mutate(TC_year = TC / (2023 - PY)) 

# Setting rownames
rownames(M) <- M$XX
```

# Bibliographic coupling communities

```{r}
cutof_edge_bib = 1
cutof_node_bib = 2
com_size_bib = 1
com_n_seed = 5
```

```{r}
g_bib  <- M  %>% biblioNetwork(analysis = "coupling", network = "references", sep = ";", shortlabel =  FALSE) %>% 
  igraph::graph_from_adjacency_matrix(mode = "undirected", weighted = TRUE, diag = FALSE) %>% 
  igraph::simplify() %>%
  as_tbl_graph(directed = FALSE)
```

```{r}
# Restrict the network
g_bib <- g_bib %E>% 
  filter(weight >= cutof_edge_bib)  %N>%
  filter(!node_is_isolated()) %N>%
  mutate(dgr = centrality_degree(weights = weight)) %N>% 
  filter(dgr >= cutof_node_bib) %N>%
  # JAccard weighting
  left_join(M %>% select(XX, PY, CR_n, TC_year), by = c("name" = "XX")) %E>% 
  mutate(weight_jac = weight / (.N()$CR_n[from] + .N()$CR_n[to] - weight) ) %E>%
  mutate(weight_jac = if_else(weight_jac > 1, 1, weight_jac) ) %N>%
  mutate(dgr_jac = centrality_degree(weights = weight_jac)) %N>%
  # Community Detection
  mutate(com = group_louvain(weights = weight_jac)) %>%
  morph(to_split, com) %>% 
  mutate(dgr_int = centrality_degree(weights = weight_jac)) %N>%
  unmorph()
```


```{r}
g_bib %N>% as_tibble() %>% count(com, sort = TRUE)
```

```{r}
# Community size restriction
g_bib <- g_bib %N>%
  # Update degree
  mutate(dgr = centrality_degree(weights = weight),
         dgr_jac = centrality_degree(weights = weight_jac))
```

# Seed articles

```{r}
### Merge with main data
seed <- M %>% select(XX, AU, PY, TI, UT) %>% inner_join(g_bib %N>% as_tibble() %>% select(name, dgr, dgr_jac, com, dgr_int), by = c('XX' = 'name')) %>%
  distinct(XX, .keep_all = TRUE) %>%
  group_by(com) %>%
    mutate(n_com = n()) %>%
    slice_max(dgr_int, n = com_n_seed, with_ties = FALSE) %>%
  ungroup() %>%
  select(com, n_com, dgr_int, PY, TI, AU, UT) %>%
  arrange(com, desc(dgr_int))
```

```{r}
seed %>% write_csv( paste0('../output/seed/scopus_', str_to_lower(var_inst), '_', str_to_lower(var_dept), '_seed.csv'))
```

```{r}
seed %>% 
  filter(n_com >= com_size_bib) %>%
  group_by(com) %>%
  slice_max(dgr_int, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  pull(UT) %>%
  paste0('EID(', .,')', collapse = ' OR ') 
```



